### PR TITLE
PIA-4391_fix_delete_icon_interaction

### PR DESCRIPTION
**Pull request by zladzeyka**
- Fix the `delete button`  interaction by adding all cell subviews to its `contentView` on the `Review screen`
 - Fix the subviews adding to its `contentView`  for cells on the `Help menu screen`, `Gallery screen`, inside capture suggestion cell - used in `No results` for image analysis, `Help Tips screen`.

### CODE REVIEW

**Comment by ValentinaIancu-Gini** [comment]
@zladzeyka I think we also need to add the custom views inside the contentView in `CaptureSuggestionsCollectionHeader`

**Comment by ValentinaIancu-Gini** [comment]
Also, all the constraints should be added between custom views and the content view not self. We need to change this in all the cells where we modified where we are adding the custom views.

**Comment by zladzeyka** [comment]
> @zladzeyka I think we also need to add the custom views inside the contentView in `CaptureSuggestionsCollectionHeader`

CaptureSuggestionsCollectionHeader : UICollectionReusableView : UIView -> It doesn't have a contentView

**Comment by ValentinaIancu-Gini** [comment]
> > @zladzeyka I think we also need to add the custom views inside the contentView in `CaptureSuggestionsCollectionHeader`
> 
> CaptureSuggestionsCollectionHeader : UICollectionReusableView : UIView -> It doesn't have a contentView

Pff I was checking apple documentation for UICollectionReusableView and I've scrolled down and saw a contentview but not I saw that is from UICollectionCell and not from UICollectionReusableView...sorry for the confusion.

**Comment by zladzeyka** [comment]
> Also, all the constraints should be added between custom views and the content view not self. We need to change this in all the cells where we modified how we are adding the custom views.

Good point, I've updated it.

**Review by ValentinaIancu-Gini — APPROVED** [review]

**Comment by ValentinaIancu-Gini** [comment]
@zladzeyka I fixed all the suggestions and comments :D.

**Review by a-szotyori — APPROVED** [review]
Looks good to me!

**Pull request merged**
