### PR TITLE
Pia 3505 enter manually title text color is wrong

### PR DESCRIPTION
**Pull request by vizaknaidavid**
image

### CODE REVIEW

**Comment by zladzeyka** [comment]
[Suggestion]I've checked the [design](https://www.figma.com/file/m4OtCvxWxPMeB0Z5k4Aeow?embed_host=share&kind=&node-id=606%3A8935&t=yzwlXqwA4gbKYKzj-1%22&viewer=1) in the dark mode `Enter manually` doesn't have any border.

**Review by zladzeyka — COMMENTED** [review]
Please 🙏 look at my comment about the border for `Enter manually`

**Comment by vizaknaidavid** [comment]
> [Suggestion] I've checked the [design](https://www.figma.com/file/m4OtCvxWxPMeB0Z5k4Aeow?embed_host=share&kind=&node-id=606%3A8935&t=yzwlXqwA4gbKYKzj-1%22&viewer=1) in the dark mode `Enter manually` doesn't have any border.

Actually the border is not there if you enter the screen in dark mode already. The border is there because I created a screenshot after switching to dark mode wen already on the screen. 

Simulator Screen Shot - iPad mini (6th generation) - 2023-01-18 at 10 33 19

**Review by zladzeyka — APPROVED** [review]
👏🏻

**Pull request merged**
