### PR TITLE
Start emulator before run tests

### PR DESCRIPTION
**Pull request by GeraltRiv**

### CODE REVIEW

**Comment by GeraltRiv** [comment]
@zladzeyka 
https://github.com/gini/gini-mobile-ios/actions/runs/11631857184
Passed.

**Comment by ValentinaIancu-Gini** [comment]
Oh wow, @GeraltRiv.  I guess with this change we will not have any more issues with timeout when running tests. Right?

**Comment by GeraltRiv** [comment]
> Oh wow, @GeraltRiv. I guess with this change we will not have any more issues with timeout when running tests. Right?

I hope it will help. 
We need to test it in real life, when everyone will create a PR's

**Review by ValentinaIancu-Gini — APPROVED** [review]
@GeraltRiv Thanks. Let's try this change.

**Review by zladzeyka — APPROVED** [review]
Thank you @GeraltRiv

**Pull request merged**
