### PR TITLE
Pia 3611 update UI ra onboarding

### PR DESCRIPTION
**Pull request by vizaknaidavid**
pr

### CODE REVIEW

**Review by vizaknaidavid — COMMENTED** [review]
I opened up the MultiLineTitleButton as public in order to use it in BankSDK, is that ok? 
If so, I have to document it. (with `internal only` mention, right?)

**Review by zladzeyka — COMMENTED** [review]
Looks good!

**Review by zladzeyka — COMMENTED** [review]
@vizaknaidavid We need to adjust the insets for the text on the Digital Invoice Onboarding screen for the iPad:
https://www.figma.com/file/m4OtCvxWxPMeB0Z5k4Aeow/Gini-Photo-Payment-%2F-iOS?node-id=1111%3A38429&t=ba5DyWaGbYd2b5DJ-1

**Review by zladzeyka — APPROVED** [review]
👍🏻

**Pull request merged**
