### PR TITLE
PIA 4627 Detecting IBAN on the iPad landscape and upside down

### PR DESCRIPTION
**Pull request by ValentinaIancu-Gini**
- fixes the device orientation and text orientation for `VNImageRequestHandler`
- fixes camera frame view after rotating the device to the right(landscape) and back, to the left, to portrait
- fixes IBAN detection Upside down
- isolates the usage of `UIApplication.shared.statusBarOrientation` because starting with iOS 13.0 will be deprecated

PIA-4627

### CODE REVIEW

**Review by zladzeyka — COMMENTED** [review]
Looks great, tested on iPad mini and it works as expected.
A tiny wish to fix a start screen in landscape orientations

Screenshot 2023-11-14 at 11 38 35

**Comment by ValentinaIancu-Gini** [comment]
@zladzeyka I fixed your suggestions. Thanks!

**Review by zladzeyka — APPROVED** [review]
👏🏻

**Comment by ValentinaIancu-Gini** [comment]
[BSDK-65](https://ginis.atlassian.net/browse/BSDK-65)
Detecting IBAN on the iPad landscape and Upside down

**Pull request merged**
